# Prometheus configuration for MOTHRA monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mothra'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mothra'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
